# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
	
    - name: '.NET: Setup'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: 'CSharpier: Check Formatting'
      run: |
          dotnet tool restore
          dotnet csharpier --check .
  	  
    - name: Build
      run: dotnet build Nwu.Aiitsa/Nwu.Aiitsa.sln
